branches:
  only:
    - master
matrix:
  include:
    - stage: 'Lint'
      language: node_js
      os: linux
      node_js: '10'
      script:
        - cd src && npm run ci.tslint
    - stage: 'WebPack'
      os: osx
      env:
        - WebPack="iOS"
      osx_image: xcode10
      language: node_js
      node_js: '10'
      jdk: oraclejdk8
      before_install:
        - pip install --upgrade pip
        - pip install --user --upgrade matplotlib
        - pip install six
      before_script: pod repo update
      script:
        - cd src && npm run build
        - cd ../demo && npm i && tns build ios --env.uglify
        - cd ../demo-angular && npm i && tns build ios --env.uglify
    - language: android
      os: linux
      env:
        - WebPack="Android"
      jdk: oraclejdk8
      before_install: nvm install 10
      script:
        - cd src && npm run build
        - cd ../demo && npm i && tns build android --env.uglify --env.snapshot
        - cd ../demo-angular && npm i && tns build android --env.uglify --env.snapshot
    - stage: 'Build'
      os: linux
      language: android
      env:
        - BuildAndroid="28"
      jdk: oraclejdk8
      before_install: nvm install 10
      script:
        - cd src && npm run build
        - cd ../demo && npm i && tns build android
        - cd ../demo-angular && npm i && tns build android
        - cd ../demo-vue && npm i && tns build android
    - os: osx
      env:
        - BuildiOS="12"
        - Xcode="10"
      osx_image: xcode10
      language: node_js
      node_js: '10'
      jdk: oraclejdk8
      before_install:
        - pip install --upgrade pip
        - pip install --user --upgrade matplotlib
        - pip install six
      before_script: pod repo update
      script:
        - cd src && npm run build
        - cd ../demo && npm i && tns build ios
        - cd ../demo-angular && npm i && tns build ios
        - cd ../demo-vue && npm i && tns build ios

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_install:
  - sudo pip install --upgrade pip
  - sudo pip install six

install:
  - echo no | npm install -g nativescript
  - echo no | npm install -g typescript
  - tns usage-reporting disable
  - tns error-reporting disable
